### ISSUE TITLE
Makefile Changes

### ISSUE THREAD

**Issue by pbrena** [endail/hx711#82]
Hello,

I'm currently writing a Gentoo ebuild file (with a lot of help from maintainers) in order  to install your Library using the Distribution's canonic methods.

While doing so I've been pointed out a couple of details in the Makefile subject to improvement that I submit to your consideration:

a) There's advice against the use of ldconfig as it causes problems in restricted environments. See for example [this reported issue](https://github.com/avxsynth/avxsynth/issues/53 )

b) Currently compilation do not support parallelism (make -jN for values of N greater than 1) which is a common practice in the distribution as it is often intensive in compilation tasks. It causes a so called "racing conflict”: using the flag -lhx711 compiling some sources before it is actually available.

Regards
Pablo

**Comment by endail** [comment]
Hi,

Just to be clear, you would like me to remove `ldconfig` from the Makefile?

**Comment by pbrena** [comment]
Yes, it breaks some restricted environments such as Gentoo’s sandbox

**Comment by endail** [comment]
This is fixed now. I've replaced it with a message to manually invoke `ldconfig`.

Out of interest, did you have the same problem with lgpio as well? [The Makefile uses ldconfig too](https://github.com/joan2937/lg/blob/master/Makefile#L135).

**Comment by pbrena** [comment]
Thanks a lot.
I did not.... I used the one in github and not the one included in hx711 thou. maybe they have difefent makefiles?
    On Tuesday, 17 January 2023, 10:54:53 PM GMT-6, Daniel Robertson ***@***.***> wrote:  
 
 


This is fixed now. I've replaced it with a message to manually invoke ldconfig.

Out of interest, did you have the same problem with lgpio as well? The Makefile uses ldconfig too.
