### ISSUE TITLE
Question about test

### ISSUE THREAD

**Issue by OldaHorak** [endail/hx711#83]
I used the guide to test but it didn't works:

`pi@Pivo:~/hx711 $ g++ -Wall -o prog main.cpp -lhx711 -llgpio`
`pi@Pivo:~/hx711 $ ./prog 23 24 -23 156209`
`./prog: error while loading shared libraries: libhx711.so: cannot open shared object file: No such file or directory`
`pi@Pivo:~/hx711 $ sudo ./prog 23 24 -23 156209`
`./prog: error while loading shared libraries: libhx711.so: cannot open shared object file: No such file or directory`

The callibration and simple & advanced tests works well.
What I do bad?
Thanks.

**Comment by endail** [comment]
Did you run `sudo make install`?

You may also need to run `ldconfig` afterward.

**Comment by OldaHorak** [comment]
Thanks for the kick up, the `sudo ldconfig` is the way. Thanks again.
