### ISSUE TITLE
Using both channels, hx711 is wired two sensors.

### ISSUE THREAD

**Issue by seliimsi** [endail/hx711#87]
Hello, Does the library make it possible to use both channels on same pins, changing the channels alternately ? For instance Can I create two different objects with same inputs except the channel input as it follows:

Hx711 hx1(data,clock,..channel='A');
Hx711 hx2(data,clock...channel='B');

Something like this.. ?

**Comment by endail** [comment]
Hi,

The HX711 is only capable of reading from one channel at a time. To be able to read from a different channel, the HX711 needs its configuration to be changed on the chip.

It would be best to create a single HX711 object and use the [`setConfig`](https://github.com/endail/hx711/blob/ed1da427e61d371b69ccad29f7b816243cd7299d/include/HX711.h#L127) method to change between channels.

Also keep in mind that Channel A can use a gain of 128 or 64. Channel B can only use 32.

**Comment by seliimsi** [comment]
Thank you so much

**Comment by seliimsi** [comment]
Hello, I tried with common CLK pin and different data pins. This type of configuration works well on rp3. The issue can be closed, your library fit best for my application. Thanks again..
